apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cost-engine
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/ianwong123/kubernetes-cost-optimiser.git
    targetRevision: main
    path: /deployments/cost-engine
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true