apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: google-online-boutique
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ianwong123/kubernetes-cost-optimiser.git
    targetRevision: main
    path: deployments/google-online-boutique
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
