server:
  service:
    type: ClusterIP
    port: 80
  persistentVolume:
    enabled: true
    size: 50Gi

  global:
    scrape_interval: 15s
    evaluation_interval: 15s

extraScrapeConfigs: |
  - job_name: 'cost-engine'
    static_configs:
      - targets: ['cost-engine:8000']