---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: databases
spec:
  encryptedData:
    password: AgAmG1lrX4rWCdWIX1DQpXLANxQyzO++3frzPDykE22GvtctTu2RlpLaO+ci9cq9iwQH6SrHf3NPpr92VNaJwkibKdDi9giKjuzXqrm30BaUKipKEhAYuWNHyd88MeIFvbv1WTH3IJe5ej59CLYwYAuICDDvBytCR8w4UxgDJe3FYBC6IbHm1D50FUnIth5C5nUoxnN0p9pbr1QZkACHo0oS/H3R5jOlCGJHR1qar2gt6If6NA/ML/0j4CcvclJHQidBVXJUJw8p3EkBEl1nxbXhm6jng+nqii72UEzWMZdYv6hsI7Sh1GCw6Igxc9UmIj3OnXmEWKGG7t85nEids+oX56+rjFCW7pMFy6CibC5ULn+bPbExkW4G5eDXwiejfWUa9C8UFimd8m2QBjCKPjG1yCm8OLvwlBBGPH91Fhq22e12EqoZKZ1IHqDXKvoYVzu06crBaee5+dJvr6QBoTqXXqPZxvHPzVuIHZ6g/8PM5KP9Evd/r7qzfXv1uzx1JRDRk/4p5KvMYj5wQ0VLC1WHL3gLR7sz/FIlN0gdNdwjxtDFrXAT2Z0PHoZZivbdsKnDO642YjYUr2C56kdCvC9399t/PnEDCBb6oPyPsM6I9tFJCZ1WzQ5r2PLpJGc8cWeKv3mAPTgdqeBDhY/9N/OypUo8R0LtjVd0aE6EmoMlWFNm0zh/UWBl183/sLD+iUbH31qaRh5vUEU2
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: databases
