apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecasting
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: forecasting
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: forecasting
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 2000    
      containers:
      - name: forecasting
        image: wongian123/forecasting:latest
        ports:
        - containerPort: 8002
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          initialDelaySeconds: 45
          periodSeconds: 10
          httpGet: 
            path: /metrics
            port: 8002
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
          httpGet:
            path: /metrics
            port: 8002
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: forecasting
  namespace: monitoring
spec:
  selector:
    app: forecasting
  ports:
  - port: 8002
    targetPort: 8002
    name: metrics
  type: ClusterIP
