apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-engine
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-engine
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: cost-engine
    spec:
      containers:
      - name: cost-engine
        image: wongian123/cost-engine:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: cost-engine
  namespace: monitoring
spec:
  selector:
    app: cost-engine
  ports:
  - port: 8000
    targetPort: 8000