apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: demo-cost-optimiser
servers: 1
agents: 2
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: 6443
ports:
  - port: 80:80
    nodeFilters:
    - loadbalancer
  - port: 8080:80
    nodeFilters: 
    - loadbalancer
  - port: 8443:443
    nodeFilters:
    - loadbalancer

