apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack
  namespace: databases 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        # image for Vector Search
        image: redis/redis-stack-server:7.2.0-v9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        
        # LOAD PASSWORD INTO ENV
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              # match SealedSecret metadata.name
              name: redis-secret  
              # matche SealedSecret spec.encryptedData key
              key: password       
        
        # USE ENV IN STARTUP COMMAND
        # tell Redis to require a password
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
        
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: databases
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379